### ISSUE TITLE
Secrets are missed when scanning the output of a trufflehog scan

### ISSUE THREAD

**Issue by anuraagbaishya** [trufflesecurity/trufflehog#1534]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### TruffleHog Version
trufflehog 3.44.0

### Expected Behavior

Trufflehog should find 2 RSA keys and 2 slack webhooks

### Actual Behavior

Trufflehog only finds 2 RSA keys

### Steps to Reproduce

1. Scan file testfile.txt from gist and save to a file `trufflehog filesystem testfile.txt --no-verification > res.txt` (File added to gist here: https://gist.github.com/anuraagbaishya/20d0e1f8381e33364dec6eade44e939b#file-testfile-txt)
2. Observe in `res.txt` trufflehog finds 2 RSA keys and 2 slack webhooks as expected. (Result added to gist here: https://gist.github.com/anuraagbaishya/20d0e1f8381e33364dec6eade44e939b#file-trufflehog-out-txt)
3. Scan `res.txt` with trufflehog `trufflehog filesystem res.txt --no-verification`
4. Observe the result only has 2 RSA keys and no slack webhooks (Result added to gist here: https://gist.github.com/anuraagbaishya/20d0e1f8381e33364dec6eade44e939b#file-trufflehog-out-scan-trace-txt)

## Environment
 * OS: Mac OS
 * Version Ventura 13.3

## Additional Context
I am not sure what causes this weird bug and if the fact that the second scan is of a trufflehog output makes any difference. 

* #0000

**Comment by ahrav** [comment]
I think https://github.com/trufflesecurity/trufflehog/releases/tag/v3.48.0 should resolve the issue here.

**Comment by react-native-mapbox-gl** [comment]
still seeing issues. Trufflehog not detecting all the secrets in the file.

**Comment by ahrav** [comment]
@anuraagbaishya @react-native-mapbox-gl going to close this specific issue as I believe the filesystem scan should be picking up secrets in files that aren't archived. Feel free to re-open if for any reason you are still seeing secrets not get detected in regular files. I'll open a separate Issue for the missed secrets in archived files.
